name: Android Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: add keys
      env:
        KEYS: ${{ secrets.KEYS }}
      run: echo $KEYS > app/src/main/res/values/keys.xml

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
